### ISSUE TITLE
How to guarantee the invertibility of conv1x1?

### ISSUE THREAD

**Issue by TRUMANCFY** [yolu1055/conditional-glow#2]
For conv1x1, we need to calculate the inverse of the weight. However, there is no guarantee to initialize the weight as an orthogonal matrix
https://github.com/yolu1055/conditional-glow/blob/eb13fa7f77a46eb1d0adcdfe0f9ea46629d7a153/modules.py#L182

**Comment by yolu1055** [comment]
We cannot guarantee the invertibility of W. Based on [this paper](https://arxiv.org/pdf/1901.11137.pdf), the invertibility guarantee is not necessary. This is because when we train the model, we maximize the log-likelihood, which implicitly pushes the determinant of W away from 0.

**Comment by TRUMANCFY** [comment]
Thank you so much for your reply. What is more, could you please provide the codes for other tasks, for example, Multi-class Segmentation? Thank you in advance.

**Comment by yolu1055** [comment]
Sorry, we don't have a plan to release code for other tasks. It is actually very easy to generalize the code to other tasks. The main changes you will need to make are (1) write a new data loader for the new dataset, (2) reset the c-glow parameters and dataset parameters for the new dataset in `train_main.py`.

**Comment by TRUMANCFY** [comment]
Thank you so much for your reply. I will further check based on your guideline.
